### PR TITLE
Call To Action / Header

### PR DESCRIPTION
**Pull request by alvarotrujillo**
- header removed from saved_cocktails for better flow from adding ingredients
- call to action now takes you to adding ingredients 
Screenshot 2022-09-02 at 1 05 09 PM

### CODE REVIEW

**Review by A-drienne — COMMENTED** [review]
Love to see cleaner and better pages!

**Review by ghost — CHANGES_REQUESTED** [review]
# app/views/components/_banner.html.erb 
it does not have the proper href path... missing _path

**Comment by alvarotrujillo** [comment]
cocktails_path won't work, so I am keeping href="cocktails"

**Review by onofrecc — COMMENTED** [review]
amazing

**Pull request merged**
