### PR TITLE
Layout and text changes

### PR DESCRIPTION
**Pull request by A-drienne**
- changed text metadata (typos)
- changed text landing page (more clarity, better phrasing)
- changed layout landing page text (title and instructions margins)
- changed icon search bar

### CODE REVIEW

**Comment by A-drienne** [comment]
image

**Comment by alvarotrujillo** [comment]
I would keep the original text on the cocktails page, and keep the search bar placeholder text too. 

Landing Page changes look good to me, as does the + symbol for the 'add ingredients'. 

Nice work!

**Comment by A-drienne** [comment]
image

**Comment by A-drienne** [comment]
image

**Review by alvarotrujillo — APPROVED** [review]
As detailed in comment. Landing Page change and navbar + looks good to me. Rest, I'd keep as is

**Review by alvarotrujillo — COMMENTED** [review]
Nice!

**Pull request merged**
